---
name: ping-app
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
  - name: ping-app
    version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: ping-app
  instances: 3
  jobs:
    - name: ping-app
      properties:
        port: 8081
        ping_interval: 60
  vm_type: default
  stemcell: default
  networks:
  - name: default

update:
  canaries: 0
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
