---
name: ping-app

addons:
- name: bpm
  jobs:
    - name: bpm
      release: bpm

releases:
  - name: ping-app
    version: create
    url: file:///Users/d058546/workspace/ping-app-release
  - name: bpm
    version: 0.3.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.3.0
    sha1: e2a86f05578257d2827a7face5531b9529fd46a5

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: ping-app
  release: ping-app
  instances: 3
  azs: [z1]
  jobs:
    - name: ping-app
      properties:
        port: 8081
        ping_interval: 60
  vm_type: default
  stemcell: default
  networks:
    - name: default

update:
  canaries: 0
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
